version: '2'
services:
    dbdemo-app:
        image: dbdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dbdemo-mysql:3306/dbdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    dbdemo-mysql:
        extends:
            file: mysql.yml
            service: dbdemo-mysql
